# Generated by Django 5.2.12 on 2026-05-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=30),
        ),
    ]
