# Generated by Django 5.2.12 on 2026-05-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_likes_alter_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_tag',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
